name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Pack
      run: dotnet pack DomsUtils/DomsUtils.csproj --no-build --configuration Release --output ./artifacts

    - name: Publish to NuGet.org
      #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        dotnet nuget push ./artifacts/*.nupkg \
          --source https://api.nuget.org/v3/index.json \
          --api-key $NUGET_API_KEY \
          --skip-duplicate

      - name: Prepare wiki content
        if: github.event_name == 'push'
        run: |
          mkdir wiki-pages
          cp README.md wiki-pages/Home.md
          find DomsUtils -name README.md | while read f; do
            rel=${f#DomsUtils/}
            page=${rel%/README.md}
            page=${page//\//-}
            cp "$f" "wiki-pages/${page}.md"
          done

      - name: Publish readmes to wiki
        if: github.event_name == 'push'
        uses: SwiftDocOrg/github-wiki-publish-action@1.0.0
        with:
          path: wiki-pages
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
